### ISSUE TITLE
I have some questions about pre trained models

### ISSUE THREAD

**Issue by MakkaPakka-sc** [JIAOJIAYUASD/dilateformer#10]
I have encountered this problem. May I ask what may be the reason for it？
`Traceback (most recent call last):
  File "main.py", line 502, in <module>
    main(args)
  File "main.py", line 279, in main
    pos_embed_checkpoint = checkpoint_model['pos_embed']
KeyError: 'pos_embed'`

**Comment by JIAOJIAYUASD** [comment]
The problem may be the version of timm, try timm == 0.5.4
