### ISSUE TITLE
when I use the DilateBlock ,an error occur

### ISSUE THREAD

**Issue by ThePengg** [JIAOJIAYUASD/dilateformer#12]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 1]], which is output 0 of Permuteward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later.The error pointing qkv = self.qkv(x).reshape(B, 3, self.num_dilation, C//self.num_dilation, H, W).permute(2, 1, 0, 3, 4, 5)

**Comment by Matsuri247** [comment]
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 1]], which is output 0 of Permuteward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later.The error pointing qkv = self.qkv(x).reshape(B, 3, self.num_dilation, C//self.num_dilation, H, W).permute(2, 1, 0, 3, 4, 5)

I apply MSDA to my own work and I get similar problem, too (I've checked that my forward pass is OK, but the error occurs when i start training). RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [20, 16, 160, 160]], which is output 0 of PermuteBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by Matsuri247** [comment]
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 1]], which is output 0 of Permuteward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later.The error pointing qkv = self.qkv(x).reshape(B, 3, self.num_dilation, C//self.num_dilation, H, W).permute(2, 1, 0, 3, 4, 5)

I get the same error point: qkv = self.qkv(x_).reshape(B, 3, self.num_dilation, C//self.num_dilation, H, W).permute(2, 1, 0, 3, 4, 5)

**Comment by Guoli-w** [comment]
hi, how to fix it?

**Comment by Guoli-w** [comment]
i have modify the DilateBlock's forward as follows:
def forward(self, x):
        if self.cpe_per_block:
            x = x + self.pos_embed(x)
        x = x.permute(0, 2, 3, 1).contiguous()
        x = x + self.drop_path(self.attn(self.norm1(x.clone())))
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        x = x.permute(0, 3, 1, 2).contiguous()
        return x
       
       i have fix it.

**Comment by ThePengg** [comment]
> i have modify the DilateBlock's forward as follows: def forward(self, x): if self.cpe_per_block: x = x + self.pos_embed(x) x = x.permute(0, 2, 3, 1).contiguous() x = x + self.drop_path(self.attn(self.norm1(x.clone()))) x = x + self.drop_path(self.mlp(self.norm2(x))) x = x.permute(0, 3, 1, 2).contiguous() return x
> 
> ```
>    i have fix it.
> ```

thanks

**Comment by Oussamab21** [comment]
Hi I get this error :

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 192, 16, 16]], which is output 0 of AsStridedBackward0, is at version 3; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Does any one have an idea ?
