### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation ...

### ISSUE THREAD

**Issue by Oussamab21** [JIAOJIAYUASD/dilateformer#13]
Hi if I try to run the code I get this error :  

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 192, 16, 16]], which is output 0 of AsStridedBackward0, is at version 3; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Does any one have an idea ?

**Comment by buziran** [comment]
have you fixed  it?

**Comment by Oussamab21** [comment]
Hi there no, do you have an idea?

**Comment by kingback2019** [comment]
you can change file 'models/dilateformer.py' line 74:
~~~python
        #before
        qkv = self.qkv(x).reshape(B, 3, self.num_dilation, C//self.num_dilation, H, W).permute(2, 1, 0, 3, 4, 5)
        #new
        qkv = self.qkv(x.clone()).reshape(B, 3, self.num_dilation, C//self.num_dilation, H, W).permute(2, 1, 0, 3, 4, 5)
~~~
