### ISSUE TITLE
Are you planning to publish pre-trained weight?

### ISSUE THREAD

**Issue by navinranjan7** [JIAOJIAYUASD/dilateformer#3]

**Comment by JIAOJIAYUASD** [comment]
Yes, we will publish the IMNT pre-trained weight of our models soon.发自我的荣耀手机-------- 原始邮件 --------发件人： Navin Ranjan ***@***.***>日期： 2023年4月2日周日 清晨5:38收件人： JIAOJIAYUASD/dilateformer ***@***.***>抄送： Subscribed ***@***.***>主    题： [JIAOJIAYUASD/dilateformer] Are you planning to publish pre-trained weight? (Issue #3)

**Comment by JIAOJIAYUASD** [comment]
The IMNT-1k pre-trained weights have released.
