### ISSUE TITLE
training question

### ISSUE THREAD

**Issue by 1072010918** [JIAOJIAYUASD/dilateformer#6]
Hello, I think your work is really interesting. I tried to use tiny model as a feature boast module, so i take different stage`s result as output. But when training, it comes out this question :  one of the variables need to gradient computation has been modified by inplace operation. Could you help me?
The question happens in the following code:
      def forward(self,x):
            x  =  self.patch_embed(x)
            y = []
            for stage in self.stage:
                  y.append(x)
                  x = stage(x)
      return y

**Comment by JIAOJIAYUASD** [comment]
modify your code like this:
x = self.patch_embed(x)
y = []
y.append(x)
for stage in self.stage:
x = stage(x)
y.append(x)
return y

I see your your code, the feature of last stage is not append in the list y. I think the problem is on this.

**Comment by 1072010918** [comment]
Hello， I tried this way，and use IDAUP to aggregate the different stages` feature, but it still has the problem that inplace operation caused. How can i solv this problem QAQ?

**Comment by JIAOJIAYUASD** [comment]
try y.append(x.copy())

**Comment by 1072010918** [comment]
Still that problem，I think maybe stage moudle has some inplace operation that i didn't find yet. I would try use different variable to get different stage` output

**Comment by Scott-che** [comment]
Hi, maybe you can see issue #2.

**Comment by 1072010918** [comment]
> Hi, maybe you can see issue #2.

ok，i will try tomorrow
