### ISSUE TITLE
About SWDA

### ISSUE THREAD

**Issue by mlkk518** [JIAOJIAYUASD/dilateformer#9]
Thanks for your sharing. It seems to be difficult to find the corresponding code for the Sliding Window Dilated Attention (SWDA) in this project. Could you please give me a hint? Thanks very much!

**Comment by JIAOJIAYUASD** [comment]
[models](https://github.com/JIAOJIAYUASD/dilateformer/tree/main/models)
/dilateformer.py

the class of DilateAttention is SWDA.

**Comment by mlkk518** [comment]
Thanks for your reply! 


-----原始邮件-----
发件人:JIAOJIAYUASD ***@***.***>
发送时间:2023-11-27 10:58:02 (星期一)
收件人: JIAOJIAYUASD/dilateformer ***@***.***>
抄送: Mlkk ***@***.***>, Author ***@***.***>
主题: Re: [JIAOJIAYUASD/dilateformer] About SWDA (Issue #9)






models
/dilateformer.py

the class of DilateAttention is SWDA.
